<?php
$products = [
    [
        'id' => 1,
        'name' => 'Anvil',
        'description' => 'A heavy metal anvil.',
        'price' => 49.99,
        'image' => '1.jpg',
    ],
    [
        'id' => 2,
        'name' => 'Axle Grease',
        'description' => 'High-quality grease for your axles.',
        'price' => 9.99,
        'image' => '2.jpg',
    ],
    [
        'id' => 3,
        'name' => 'Atom Re-Arranger',
        'description' => 'Rearrange atoms at your whim.',
        'price' => 999.99,
        'image' => '3.jpg',
    ],
    [
        'id' => 4,
        'name' => 'Bed Springs',
        'description' => 'Durable springs for your bed.',
        'price' => 29.99,
        'image' => '4.jpg',
    ],
    [
        'id' => 5,
        'name' => 'Bird Seed',
        'description' => 'Nutritious seed mix for birds.',
        'price' => 5.99,
        'image' => '5.jpg',
    ],
    [
        'id' => 6,
        'name' => 'Blasting Powder',
        'description' => 'Explosive powder for blasting.',
        'price' => 99.99,
        'image' => '6.jpg',
    ],
    [
        'id' => 7,
        'name' => 'Cork',
        'description' => 'Natural cork material.',
        'price' => 3.99,
        'image' => '7.jpg',
    ],
    [
        'id' => 8,
        'name' => 'Disintegration Pistol',
        'description' => 'Pistol with disintegration capabilities.',
        'price' => 499.99,
        'image' => '8.jpg',
    ],
    [
        'id' => 9,
        'name' => 'Earthquake Pills',
        'description' => 'Pills that simulate earthquakes.',
        'price' => 19.99,
        'image' => '9.jpg',
    ],
    [
        'id' => 10,
        'name' => 'Female Roadrunner costume',
        'description' => 'Costume to dress up as a female roadrunner.',
        'price' => 59.99,
        'image' => '10.jpg',
    ],
    [
        'id' => 11,
        'name' => 'Giant Rubber Band',
        'description' => 'Extra large rubber band.',
        'price' => 7.99,
        'image' => '11.jpg',
    ],
    [
        'id' => 12,
        'name' => 'Instant Girl',
        'description' => 'Create a girl instantly with this device.',
        'price' => 1999.99,
        'image' => '12.jpg',
    ],
    [
        'id' => 13,
        'name' => 'Iron Carrot',
        'description' => 'A carrot made of iron.',
        'price' => 14.99,
        'image' => '13.jpg',
    ],
    [
        'id' => 14,
        'name' => 'Jet Propelled Unicycle',
        'description' => 'Unicycle with a jet engine.',
        'price' => 299.99,
        'image' => '14.jpg',
    ],
    [
        'id' => 15,
        'name' => 'Out-Board Motor',
        'description' => 'Motor for use outside of the water.',
        'price' => 129.99,
        'image' => '15.jpg',
    ],
    [
        'id' => 16,
        'name' => 'Railroad Track',
        'description' => 'Straight railroad track segment.',
        'price' => 89.99,
        'image' => '16.jpg',
    ],
    [
        'id' => 17,
        'name' => 'Rocket Sled',
        'description' => 'Sled propelled by rockets.',
        'price' => 499.99,
        'image' => '17.jpg',
    ],
    [
        'id' => 18,
        'name' => 'Super Outfit',
        'description' => 'Outfit with superpowers.',
        'price' => 399.99,
        'image' => '18.jpg',
    ],
    [
        'id' => 19,
        'name' => 'Time Space Gun',
        'description' => 'Gun that manipulates time and space.',
        'price' => 899.99,
        'image' => '19.jpg',
    ],
    [
        'id' => 20,
        'name' => 'X-Ray',
        'description' => 'Device to see through objects.',
        'price' => 199.99,
        'image' => '20.jpg',
    ],
];
?>
